/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.


import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('offline-html-cache').then((cache) => {
      // Pre-cache the offline.html and any other essential files
      return cache.addAll([
        '/offline.html',
        "./Features.js"
        // Add other important files you want to pre-cache here
        // For example: '/index.html', '/styles.css', '/app.js', etc.
      ]);
    })
  );
});

precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
console.log('This is a custom service worker!');

registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.
     

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);


// registerRoute(
//   // Match the offline.html file
//   ({ url }) => url.pathname ==='/offline.html', 
//   new CacheFirst({
//     cacheName: 'offline-html-cache',
//     plugins: [
//       new ExpirationPlugin({
//         maxAgeSeconds: 30 * 24 * 60 * 60, // Cache for 30 days
//       }),
//     ],
//   })
// );

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>  url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

self.addEventListener('fetch', (event) => {
  // Check if the user is navigating to a page (e.g., /features, /about, etc.)
  if (event.request.mode === 'navigate') {
    if (!navigator.onLine) {
      event.respondWith(
        fetch(event.request)
          .then((response) => {
            // If the network request succeeds, return the response
            return response;
          })
          .catch(() => {
            // If the network request fails (e.g., user is offline), serve the offline.html
            return caches.match('/offline.html'); // Serve the offline page from the cache
          })
      );
     }
 
  } else {
    // For non-navigation requests, try to use the CacheFirst strategy
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        return cachedResponse || fetch(event.request);
      })
    );
  }
});



// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
